### ISSUE TITLE
Error when closing the AS3 client (window)

### ISSUE THREAD

**Issue by Knose1** [prettymuchbryce/flashio#2]
When closing the AS3  client (window) :

```js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
```

**Comment by Knose1** [comment]
Ok I added an event on the gameWindow (on my AS3 client)
![WindowsInit.gameWindow.addEventListener(Event.CLOSING, onClosed);](https://i.imgur.com/jkxeiaV.png)
that close my FlashIO's client

But I don't have any 'close' / 'disconnect' event dispatched when closing the gameWindow (on my js Server)

**Comment by Knose1** [comment]
ok my bad, the readme on npm is not updated. I saw you example and it's 'end'
![npm Events doc](https://i.imgur.com/ArvUPtZ.png)
_(on [npm](https://www.npmjs.com/package/flashio))_
